relman:
  emails:
    - csheehan@mozilla.com
  channels:
    - "#sheehan_testchan_2"

releasetasks:
  plugins:
    - irc
    - log_collect
    - ses
  emails:
    - release-automation-notification-dev@mozilla.com
  channels:
    - "#release-notifications"

releng-important:
  emails:
    - csheehan@mozilla.com
  channels:
    - "#sheehan_testchan_2"
