relman:
  emails:
    - csheehan@mozilla.com
  channels:
    - "#sheehan_testchan_2"

releasetasks:
  plugins:
    - irc
    - log_collect
    - ses
  emails:
    - release-automation-notifications-dev@mozilla.com
  channels:
    - "#release-notifications-dev"

releng-important:
  emails:
    - csheehan@mozilla.com
  channels:
    - "#sheehan_testchan_2"

connor:
  plugins:
    - irc
    - log_collect
    - ses
  channels:
    - "#sheehan_testchan_1"
  emails:
    - csheehan@mozilla.com
