releasetasks:
  plugins:
    - irc
    - log_collect
    - ses
  emails:
    - release-automation-notifications@mozilla.com
  channels:
    - "#release-notifications"

release-drivers:
  plugins:
    - ses
  emails:
    - release-drivers@mozilla.org
